{
    "temd_id": 0,
    "ware": "string",
    "part_id": "0",
    "link_id": "0",
    "year": "string",
    "date": "string",
    "code": "string",
    "fore": "string",
    "core": "string",
    "name": "string",
    "find": "string",
    "fund": "string",
    "kind": "string",
    "mark": "string",
    "task": "string",
    "text": "string",
    "give": 0,
    "fare": 0,
    "plan_cast": 0,
    "cost": 0,
    "item": "0",
    "note": "string"
  }